version: '3'
services:
  redis:
    image: redis:6.2.6-alpine3.15
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD-requirepass}
    volumes:
      - cache:/data

  elasticsearch:
    image: elasticsearch:7.17.3
    ports:
      - '9200:9200'
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms200m -Xmx200m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    
  kibana:
    image: kibana:7.7.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  api:
    build: .
    expose:
      - "8000"
    entrypoint: ["gunicorn", "main:app", "--workers", "4", "--worker-class",
                 "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
    environment:
      - REDIS_HOST=redis
      - ${REDIS_PASSWORD-requirepass}
    depends_on:
      - elasticsearch
      - redis

  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - api
    ports:
      - "80:80"
volumes:
  cache:
    driver: local
  esdata:
    external: true