version: '3'
services:
  redis:
    image: redis
    restart: always
    expose:
      - '6379'
    volumes:
      - ../redis.conf:/usr/local/etc/redis/redis.conf

  elasticsearch:
    image: elasticsearch:7.17.3
    expose:
      - '9200'
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms200m -Xmx200m

  api:
    build: .
    expose:
      - "8000"
    entrypoint: ["gunicorn", "main:app", "--workers", "4", "--worker-class",
                 "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
    environment:
      - REDIS_HOST=redis
      - ${REDIS_PASSWORD-requirepass}
    depends_on:
      - elasticsearch
      - redis

  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - api
    ports:
      - "80:80"
volumes:
  cache:
    driver: local
